spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_demo  # MySQL database URL
    username: apesin  
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver
  jpa:
    hibernate:
      ddl-auto: create  # Automatically create/drop tables based on entities
    show-sql: false  # Disable SQL logging in the console
    properties:
      hibernate:
        format_sql: true  # Format SQL queries for better readability
    database: mysql  # Specify the database type
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL dialect for Hibernate

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970  # Secret key for JWT signing
      expiration: 86400000  # JWT expiration time (24 hours in milliseconds)
      refresh-token:
        expiration: 604800000  # Refresh token expiration time (7 days in milliseconds)

logging.level.org.springframework.security: DEBUG