### Register User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "Mary",
  "lastname": "Jane",
  "email":  "maryj@mail.com",
  "password": "Pa$$w00rd",
  "role":  "ADMIN"
}

> {% client.global.set("auth-token", response.body.access_token);  %}

### Query the Demo endpoint
GET http://localhost:8080/api/demo
Authorization: Bearer {{auth-token}}
